"""
REGRESSION TEST - Style Corridor Validation
============================================
Validates that solver output matches expected corridors from manual policy.

Target Corridors (from traindata.xlsx analysis):
- 2er: 68-76% (target: 72%)
- 3er: 18-25% (target: 22%)
- 1er: 3-10% (target: 6%)
- Split-2er rate: 30-45% (target: 37%)
- Saturday 1er: 12-20% (target: 15%)

NOTE: This is a manual script, not a pytest test.
"""

import sys

# Skip at module level for pytest collection
if "pytest" in sys.modules:
    import pytest
    pytest.skip("Manual script - requires style_report.json", allow_module_level=True)

import json
from pathlib import Path


def load_style_report() -> dict:
    """Load the style report generated by the solver."""
    path = Path(__file__).parent / "data" / "style_report.json"
    if not path.exists():
        raise FileNotFoundError(f"Style report not found at {path}")
    
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def load_manual_policy() -> dict:
    """Load the manual policy for target corridors."""
    path = Path(__file__).parent / "data" / "manual_policy.json"
    if not path.exists():
        raise FileNotFoundError(f"Manual policy not found at {path}")
    
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def check_corridor(name: str, value: float, low: float, high: float, target: float) -> tuple[bool, str]:
    """Check if value is within corridor."""
    in_range = low <= value <= high
    status = "✅" if in_range else "❌"
    direction = ""
    if value < low:
        direction = f" (too low by {(low - value) * 100:.1f}%)"
    elif value > high:
        direction = f" (too high by {(value - high) * 100:.1f}%)"
    
    msg = f"{status} {name}: {value*100:.1f}% (target: {target*100:.0f}%, corridor: {low*100:.0f}-{high*100:.0f}%){direction}"
    return in_range, msg


def main():
    print("=" * 60)
    print("REGRESSION TEST - Style Corridor Validation")
    print("=" * 60)
    
    # Load data
    try:
        report = load_style_report()
        policy = load_manual_policy()
    except FileNotFoundError as e:
        print(f"ERROR: {e}")
        print("Run the solver first to generate style_report.json")
        return 1
    
    # Extract values
    block_mix = report.get("block_mix_overall", {})
    by_day = report.get("block_mix_by_day", {})
    split_rate = report.get("split_2er_rate", 0)
    template_rate = report.get("template_match_rate", 0)
    
    # Policy targets
    policy_mix = policy.get("target_block_mix_overall", {})
    policy_split = policy.get("split2_rate_overall", 0.37)
    
    results = []
    
    print("\n📊 BLOCK MIX CORRIDORS")
    print("-" * 40)
    
    # 2er corridor: 68-76%
    ok, msg = check_corridor(
        "2er mix", 
        block_mix.get("2er", 0), 
        0.68, 0.76, 
        policy_mix.get("2er", 0.72)
    )
    results.append(ok)
    print(msg)
    
    # 3er corridor: 18-25%
    ok, msg = check_corridor(
        "3er mix", 
        block_mix.get("3er", 0), 
        0.18, 0.25, 
        policy_mix.get("3er", 0.22)
    )
    results.append(ok)
    print(msg)
    
    # 1er corridor: 3-10%
    ok, msg = check_corridor(
        "1er mix", 
        block_mix.get("1er", 0), 
        0.03, 0.10, 
        policy_mix.get("1er", 0.06)
    )
    results.append(ok)
    print(msg)
    
    print("\n📈 SPLIT RATE CORRIDOR")
    print("-" * 40)
    
    # Split-2er corridor: 30-45%
    ok, msg = check_corridor(
        "Split-2er rate", 
        split_rate, 
        0.30, 0.45, 
        policy_split
    )
    results.append(ok)
    print(msg)
    
    print("\n📅 SATURDAY 1er CORRIDOR")
    print("-" * 40)
    
    # Saturday should have higher 1er (12-20%)
    sat_1er = by_day.get("Sat", {}).get("1er", 0)
    ok, msg = check_corridor(
        "Sat 1er", 
        sat_1er, 
        0.12, 0.20, 
        0.15
    )
    results.append(ok)
    print(msg)
    
    print("\n🎯 TEMPLATE MATCHING")
    print("-" * 40)
    print(f"Template match rate: {template_rate*100:.1f}%")
    
    # Summary
    print("\n" + "=" * 60)
    passed = sum(results)
    total = len(results)
    
    if all(results):
        print(f"✅ ALL TESTS PASSED ({passed}/{total})")
        return 0
    else:
        print(f"❌ TESTS FAILED ({passed}/{total} passed)")
        return 1


if __name__ == "__main__":
    sys.exit(main())
